import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  ShieldCheck,
  FileText,
  Clock,
  CheckCircle2,
  Lock,
  Edit3,
  Calendar,
  AlertTriangle,
  FileCheck,
  History,
  Save,
  Download,
  X,
  UserCheck
} from 'lucide-react';
import { Currency } from '../../types';

export interface LegalDocument {
  id: string;
  title: string;
  slug: string;
  documentType: 'privacy_policy' | 'terms_conditions' | 'cookie_policy' | 'refund_policy' | 'service_agreement' | 'nda_template';
  version: string;
  effectiveDate: string;
  status: 'active_live' | 'draft' | 'pending_approval' | 'archived';
  lastReviewedBy: string;
  content: string;
}

interface CMSLegalComplianceProps {
  currency: Currency;
  onShowToast?: (message: string) => void;
}

export const CMSLegalCompliance: React.FC<CMSLegalComplianceProps> = ({
  currency,
  onShowToast,
}) => {
  // Legal Documents State
  const [legalDocs, setLegalDocs] = useState<LegalDocument[]>([
    {
      id: 'leg-1',
      title: 'MFS Growth Agency Privacy Policy & Data Protection Directives',
      slug: '/privacy',
      documentType: 'privacy_policy',
      version: 'v2.4',
      effectiveDate: '2026-01-01',
      status: 'active_live',
      lastReviewedBy: 'Shehroz Sultan (Founder & Legal Admin)',
      content: `At MFS Growth Agency, we prioritize client confidentiality, data privacy, and intellectual property protection. Personal information and uploaded files (PDF, DOCX, PPTX) are processed exclusively for service completion and are never shared or resold.`,
    },
    {
      id: 'leg-2',
      title: 'Terms of Service, Order Refund Policy & SLA Guarantee',
      slug: '/terms',
      documentType: 'terms_conditions',
      version: 'v3.1',
      effectiveDate: '2026-03-15',
      status: 'active_live',
      lastReviewedBy: 'Shehroz Sultan',
      content: `1. 50% Grand Launch discount is applied automatically at checkout.\n2. Revisions are supported up to 14 days after project completion.\n3. Sample work displayed under "Our Work" is protected and strictly watermarked.`,
    },
    {
      id: 'leg-3',
      title: 'Non-Disclosure Agreement (NDA) Master Template for Corporate Clients',
      slug: '/legal/nda-template',
      documentType: 'nda_template',
      version: 'v1.0',
      effectiveDate: '2026-06-01',
      status: 'active_live',
      lastReviewedBy: 'MFS Legal Advisory',
      content: `This Mutual Non-Disclosure Agreement governs confidential information exchanged between MFS Growth Agency and Corporate / Enterprise Clients...`,
    },
    {
      id: 'leg-4',
      title: 'Academic Integrity & Non-Plagiarism Service Agreement',
      slug: '/legal/academic-agreement',
      documentType: 'service_agreement',
      version: 'v2.0',
      effectiveDate: '2026-05-10',
      status: 'active_live',
      lastReviewedBy: 'Academic Quality Lead',
      content: `All academic assignments, research reports, and essays generated by MFS Growth Agency strictly follow APA, Harvard, and MLA citation standards. Deliverables serve as model research and reference material.`,
    },
  ]);

  const [selectedDoc, setSelectedDoc] = useState<LegalDocument | null>(null);
  const [isEditorOpen, setIsEditorOpen] = useState(false);

  const handleOpenEditor = (doc: LegalDocument) => {
    setSelectedDoc(doc);
    setIsEditorOpen(true);
  };

  const handleSaveLegalDoc = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedDoc) return;

    setLegalDocs((prev) =>
      prev.map((d) => (d.id === selectedDoc.id ? selectedDoc : d))
    );
    setIsEditorOpen(false);
    if (onShowToast) onShowToast(`Published updated legal document "${selectedDoc.title}" (${selectedDoc.version})`);
  };

  return (
    <div className="space-y-6">
      {/* HEADER BAR */}
      <div className="glass-card rounded-3xl border border-white/10 p-5 space-y-4 bg-[#0D0D12]">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-0.5 rounded-full bg-red-500/10 text-red-400 font-mono text-[10px] font-bold border border-red-500/30 uppercase">
                LEGAL & COMPLIANCE
              </span>
              <span className="px-2.5 py-0.5 rounded-full bg-[#28C76F]/10 text-[#28C76F] font-mono text-[10px] font-bold border border-[#28C76F]/30 flex items-center gap-1">
                <Lock className="w-3 h-3 text-[#28C76F]" />
                <span>VERSION CONTROLLED</span>
              </span>
            </div>
            <h3 className="font-poppins font-bold text-white text-base mt-1">
              Legal Documents, Privacy Policies & NDAs
            </h3>
            <p className="text-xs text-neutral-400">
              Manage client-facing terms, privacy policies, refund guarantees, NDAs, and academic compliance frameworks.
            </p>
          </div>

          <button
            onClick={() => {
              if (onShowToast) onShowToast('All active legal policies verified for global client compliance!');
            }}
            className="px-5 py-2.5 rounded-2xl bg-[#E5C158] text-black font-extrabold text-xs hover:bg-[#fce888] transition-all flex items-center gap-1.5 cursor-pointer shadow-lg shrink-0"
          >
            <ShieldCheck className="w-4 h-4" />
            <span>Audit Legal Compliance</span>
          </button>
        </div>
      </div>

      {/* LEGAL DOCUMENTS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {legalDocs.map((doc) => (
          <div
            key={doc.id}
            className="glass-card rounded-3xl border border-white/10 p-5 space-y-4 bg-[#0D0D12] hover:border-[#E5C158]/50 transition-all flex flex-col justify-between"
          >
            <div className="space-y-3">
              <div className="flex items-center justify-between gap-2">
                <span className="px-2.5 py-1 rounded-xl bg-white/5 border border-white/10 text-[#E5C158] font-mono text-[10px] font-bold uppercase">
                  {doc.documentType.replace('_', ' ')}
                </span>
                <span className="px-2.5 py-1 rounded-full bg-emerald-500/20 text-emerald-400 font-mono text-[10px] font-bold border border-emerald-500/30">
                  {doc.version} Live
                </span>
              </div>

              <strong className="text-white text-base font-bold block leading-snug">
                {doc.title}
              </strong>

              <p className="text-xs text-neutral-300 font-mono line-clamp-3 bg-white/[0.02] p-3 rounded-2xl border border-white/5 leading-relaxed">
                {doc.content}
              </p>
            </div>

            <div className="pt-3 border-t border-white/5 flex items-center justify-between text-[10px] font-mono text-neutral-400">
              <div className="flex items-center gap-2">
                <span>Effective: <strong className="text-white">{doc.effectiveDate}</strong></span>
              </div>

              <button
                onClick={() => handleOpenEditor(doc)}
                className="px-3.5 py-1.5 rounded-xl bg-white/10 hover:bg-[#E5C158] hover:text-black text-white font-bold transition-all flex items-center gap-1.5 cursor-pointer"
              >
                <Edit3 className="w-3.5 h-3.5" />
                <span>Edit Policy</span>
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* EDIT LEGAL MODAL */}
      <AnimatePresence>
        {isEditorOpen && selectedDoc && (
          <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-2xl bg-[#0D0D12] border border-white/10 rounded-3xl p-6 space-y-4 shadow-2xl"
            >
              <div className="flex items-center justify-between border-b border-white/10 pb-3">
                <div className="flex items-center gap-2 text-[#E5C158]">
                  <ShieldCheck className="w-5 h-5" />
                  <h3 className="font-poppins font-bold text-white text-base">
                    Edit Legal Document ({selectedDoc.version})
                  </h3>
                </div>
                <button
                  onClick={() => setIsEditorOpen(false)}
                  className="p-1 rounded-lg text-neutral-400 hover:text-white"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form onSubmit={handleSaveLegalDoc} className="space-y-3 text-xs">
                <div>
                  <label className="text-neutral-400 font-mono text-[10px] uppercase block mb-1">
                    Document Title
                  </label>
                  <input
                    type="text"
                    required
                    value={selectedDoc.title}
                    onChange={(e) => setSelectedDoc({ ...selectedDoc, title: e.target.value })}
                    className="w-full bg-white/[0.04] border border-white/10 rounded-2xl px-4 py-2.5 text-xs text-white focus:outline-none focus:border-[#E5C158] font-bold"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-neutral-400 font-mono text-[10px] uppercase block mb-1">
                      Version Number
                    </label>
                    <input
                      type="text"
                      value={selectedDoc.version}
                      onChange={(e) => setSelectedDoc({ ...selectedDoc, version: e.target.value })}
                      className="w-full bg-white/[0.04] border border-white/10 rounded-2xl px-3 py-2 text-xs text-white font-mono focus:outline-none focus:border-[#E5C158]"
                    />
                  </div>

                  <div>
                    <label className="text-neutral-400 font-mono text-[10px] uppercase block mb-1">
                      Effective Date
                    </label>
                    <input
                      type="date"
                      value={selectedDoc.effectiveDate}
                      onChange={(e) => setSelectedDoc({ ...selectedDoc, effectiveDate: e.target.value })}
                      className="w-full bg-white/[0.04] border border-white/10 rounded-2xl px-3 py-2 text-xs text-white font-mono focus:outline-none focus:border-[#E5C158]"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-neutral-400 font-mono text-[10px] uppercase block mb-1">
                    Legal Document Content
                  </label>
                  <textarea
                    rows={8}
                    required
                    value={selectedDoc.content}
                    onChange={(e) => setSelectedDoc({ ...selectedDoc, content: e.target.value })}
                    className="w-full bg-white/[0.04] border border-white/10 rounded-2xl px-4 py-2.5 text-xs text-white font-mono focus:outline-none focus:border-[#E5C158]"
                  />
                </div>

                <div className="pt-2 flex justify-end gap-2">
                  <button
                    type="button"
                    onClick={() => setIsEditorOpen(false)}
                    className="px-4 py-2 rounded-xl bg-white/10 text-neutral-300 font-bold"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-5 py-2 rounded-xl bg-[#E5C158] text-black font-extrabold shadow-lg"
                  >
                    Publish Legal Version
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};
